---
# Variables globales pour tous les environnements
# Ces variables sont communes à tous les groupes d'hôtes

# Configuration système
system:
  timezone: "Europe/Paris"
  locale: "fr_FR.UTF-8"
  packages:
    - curl
    - wget
    - git
    - unzip
    - htop
    - nano
    - vim
    - tree
    - jq
    - python3
    - python3-pip
    - build-essential
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - gnupg
    - lsb-release

# Configuration Docker
docker:
  version: "24.0"
  compose_version: "2.21.0"
  users:
    - "{{ ansible_user }}"
  daemon_options:
    storage-driver: overlay2
    log-driver: json-file
    log-opts:
      max-size: 10m
      max-file: "3"
  registry_mirrors: []

# Configuration Laravel
laravel:
  php_version: "8.2"
  node_version: "18"
  composer_version: "2"
  packages:
    - php-fpm
    - php-mysql
    - php-redis
    - php-mbstring
    - php-xml
    - php-gd
    - php-curl
    - php-zip
    - php-bcmath
    - php-intl

# Configuration réseau
network:
  ports:
    http: 80
    https: 443
    mysql: 3306
    redis: 6379
    mailhog: 8025
    adminer: 8080
    dozzle: 9999
    it_tools: 8081
  firewall:
    allowed_ports:
      - "22"      # SSH
      - "80"      # HTTP
      - "443"     # HTTPS
      - "8025"    # Mailhog
      - "8080"    # Adminer
      - "9999"    # Dozzle
    blocked_ports: []

# Configuration sécurité
security:
  ssh:
    port: 22
    protocol: 2
    permit_root_login: "no"
    password_authentication: "no"
    pubkey_authentication: "yes"
    max_auth_tries: 3
    max_sessions: 10
  fail2ban:
    enabled: true
    bantime: 3600
    maxretry: 5
    findtime: 600
  ufw:
    enabled: true
    default_policy: deny
    logging: "on"

# Configuration monitoring
monitoring:
  enabled: true
  retention_days: 30
  log_level: info
  services:
    - docker
    - nginx
    - mysql
    - redis
    - php-fpm

# Configuration backup
backup:
  enabled: true
  retention_days: 7
  schedule: "0 2 * * *"  # 2h du matin tous les jours
  targets:
    - database
    - uploads
    - logs
    - config

# Configuration SSL/TLS
ssl:
  enabled: true
  provider: letsencrypt
  email: admin@example.com
  staging: false
  
# Configuration des services optionnels
optional_services:
  mailhog:
    enabled: true
    environments: ["local", "development", "staging"]
  adminer:
    enabled: true
    environments: ["local", "development", "staging"]
  it_tools:
    enabled: true
    environments: ["local", "development"]
  dozzle:
    enabled: true
    environments: ["local", "development", "staging"]
  watchtower:
    enabled: true
    schedule: "0 3 * * *"  # 3h du matin tous les jours
    cleanup: true