---
# Handlers pour le rôle Nginx-Proxy

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    
- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
    
- name: test nginx
  command: nginx -t
  register: nginx_test_result
  failed_when: nginx_test_result.rc != 0