---
# Métadonnées du rôle Common

galaxy_info:
  author: Ansible Laravel Deployment
  description: Configuration de base du système pour Laravel
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  
  platforms:
    - name: Ubuntu
      versions:
        - 20.04
        - 22.04
    - name: Debian
      versions:
        - 10
        - 11
  
  galaxy_tags:
    - system
    - common
    - base
    - laravel
    - configuration

dependencies: []