---
# Variables par défaut pour le rôle Docker

# Versions par défaut
docker_version: "24.0"
docker_compose_version: "2.21.0"

# Configuration du daemon Docker
docker_daemon_config:
  storage-driver: overlay2
  log-driver: json-file
  log-opts:
    max-size: 10m
    max-file: "3"
  live-restore: true
  userland-proxy: false
  no-new-privileges: true
  default-runtime: runc
  exec-opts:
    - native.cgroupdriver=systemd
  registry-mirrors: []
  insecure-registries: []
  debug: false
  experimental: false
  metrics-addr: "0.0.0.0:9323"
  iptables: true
  ip-forward: true
  ip-masq: true
  bridge: docker0
  max-concurrent-downloads: 3
  max-concurrent-uploads: 5
  shutdown-timeout: 15

# Utilisateurs à ajouter au groupe docker
docker_users:
  - "{{ ansible_user }}"
  - "{{ app_user | default('laravel') }}"

# Configuration du nettoyage automatique
docker_cleanup:
  enabled: true
  schedule: "0 2 * * *"  # 2h du matin
  prune_containers: true
  prune_images: true
  prune_volumes: true
  prune_networks: true
  prune_build_cache: true

# Configuration des logs Docker
docker_log_rotation:
  enabled: true
  max_size: 10m
  max_files: 5
  compress: true