---
# Handlers pour le rôle Common

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    
- name: reload systemd
  systemd:
    daemon_reload: yes
    
- name: restart cron
  systemd:
    name: cron
    state: restarted