---
# Métadonnées du rôle Monitoring

galaxy_info:
  author: Ansible Laravel Deployment
  description: Surveillance et monitoring des services
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  
  platforms:
    - name: Ubuntu
      versions:
        - 20.04
        - 22.04
    - name: Debian
      versions:
        - 10
        - 11
  
  galaxy_tags:
    - monitoring
    - logs
    - alerts
    - system
    - docker

dependencies:
  - role: common