---
# Inventaire de staging pour le déploiement Laravel
# Environnement de pre-production

all:
  children:
    web_servers:
      hosts:
        staging-web-01:
          ansible_host: 192.168.1.50
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          deploy_path: /var/www/laravel-app
          project_name: laravel-staging
          
    database_servers:
      hosts:
        staging-db-01:
          ansible_host: 192.168.1.60
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa

  vars:
    # Variables globales pour l'environnement staging
    environment: staging
    timezone: Europe/Paris
    locale: fr_FR.UTF-8
    
    # Configuration Docker
    docker_version: "24.0"
    docker_compose_version: "2.21.0"
    
    # Configuration Laravel
    laravel_env: staging
    laravel_debug: false
    laravel_log_level: info
    
    # Configuration réseau
    allowed_hosts:
      - "{{ ansible_default_ipv4.address }}"
      - "127.0.0.1"
      - "localhost"
      
    # Configuration sécurité
    firewall_enabled: true
    fail2ban_enabled: true
    
    # Configuration monitoring
    monitoring_enabled: true
    log_aggregation_enabled: true