---
# Handlers pour le rôle Docker

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  
- name: reload docker
  systemd:
    name: docker
    state: reloaded