---
# Métadonnées du rôle Laravel-App

galaxy_info:
  author: Ansible Laravel Deployment
  description: Déploiement d'application Laravel avec Docker
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  
  platforms:
    - name: Ubuntu
      versions:
        - 20.04
        - 22.04
    - name: Debian
      versions:
        - 10
        - 11
  
  galaxy_tags:
    - laravel
    - php
    - web
    - deployment
    - docker

dependencies:
  - role: common
  - role: docker