# Configuration Laravel Template par défaut
project:
  name: "Laravel"
  domain: "laravel.local"
services:
  optional:
    mailhog:
      enabled: true
      environments: ["local", "development"]
    adminer:
      enabled: true
      environments: ["local", "development"]
    it-tools:
      enabled: true
      environments: ["local", "development"]
    dozzle:
      enabled: true
      environments: ["local", "development", "staging"]
network:
  ports:
    mariadb: 3306
    redis: 6379
    dozzle: 9999
environments:
  local:
    debug: true
    log_level: "debug"
  development:
    debug: true
    log_level: "debug"
  staging:
    debug: false
    log_level: "info"
  production:
    debug: false
    log_level: "error"
security:
  snyk:
    severity_threshold: "high"
    fail_on_issues: false
    monitor_enabled: true
# Configuration des packages Laravel à installer
packages:
  production:
    - name: "laravel/horizon"
      version: "*"
      required: true
    - name: "laravel/telescope"
      version: "*"
      required: true
    - name: "laravel/sanctum"
      version: "*"
      required: true
    - name: "laravel/nightwatch"
      version: "*"
      required: false
    - name: "spatie/laravel-permission"
      version: "*"
      required: true
    - name: "spatie/laravel-activitylog"
      version: "*"
      required: true
    - name: "predis/predis"
      version: "*"
      required: true
  development:
    # Core packages first (required)
    - name: "nunomaduro/collision"
      version: "^8.0"
      required: true
    - name: "barryvdh/laravel-ide-helper"
      version: "^3.0"
      required: true
    - name: "barryvdh/laravel-debugbar"
      version: "^3.15"
      required: true
    - name: "beyondcode/laravel-query-detector"
      version: "^1.8"
      required: false
      php_version: ">=8.0"
      max_laravel_version: 11
      description: "Non compatible Laravel 12 - utiliser Debugbar à la place"
    - name: "pestphp/pest"
      version: "^3.0"
      required: true
    - name: "pestphp/pest-plugin-laravel"
      version: "^3.0"
      required: true
    # Quality tools (optional - PHP 8.4 compatible versions)
    - name: "symplify/easy-coding-standard"
      version: "^12.5"
      required: false
      php_version: ">=8.1"
    - name: "rector/rector"
      version: "^2.1"
      required: false
      php_version: ">=7.4"
    - name: "larastan/larastan"
      version: "^3.0"
      required: false
      php_version: ">=8.1"
    - name: "driftingly/rector-laravel"
      version: "^2.0"
      required: false
      php_version: ">=8.0"
      description: "Règles Rector pour Laravel - v2.0 compatible Laravel 12"
    - name: "nunomaduro/phpinsights"
      version: "^2.13"
      required: false
      php_version: ">=8.1"
    # Enlightn compatible Laravel 12 (fork community)
    - name: "ivqonsanada/enlightn"
      version: "^2.0"
      required: false
      php_version: ">=8.0"
      laravel_12_compatible: true
      description: "Fork Enlightn compatible Laravel 12"
