---
# Handlers pour le rôle Laravel-App

- name: restart docker containers
  docker_compose:
    project_src: "{{ app_deploy_path }}"
    state: present
    recreate: always
    
- name: reload docker containers
  docker_compose:
    project_src: "{{ app_deploy_path }}"
    state: present
    restart: yes
    
- name: clear laravel cache
  docker_container:
    name: "{{ app_project_name }}_php"
    command: "{{ item }}"
    working_dir: /var/www/html
    detach: false
  loop:
    - "php artisan config:clear"
    - "php artisan route:clear"
    - "php artisan view:clear"
    - "php artisan cache:clear"
    
- name: optimize laravel
  docker_container:
    name: "{{ app_project_name }}_php"
    command: "{{ item }}"
    working_dir: /var/www/html
    detach: false
  loop:
    - "php artisan config:cache"
    - "php artisan route:cache"
    - "php artisan view:cache"
    - "php artisan event:cache"
  when: laravel_env == "production"