---
# Métadonnées du rôle Docker

galaxy_info:
  author: Ansible Laravel Deployment
  description: Installation et configuration de Docker pour Laravel
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  
  platforms:
    - name: Ubuntu
      versions:
        - 20.04
        - 22.04
    - name: Debian
      versions:
        - 10
        - 11
  
  galaxy_tags:
    - docker
    - containers
    - laravel
    - deployment

dependencies:
  - role: common