---
# Métadonnées du rôle Security

galaxy_info:
  author: Ansible Laravel Deployment
  description: Configuration sécurisée du système
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  
  platforms:
    - name: Ubuntu
      versions:
        - 20.04
        - 22.04
    - name: Debian
      versions:
        - 10
        - 11
  
  galaxy_tags:
    - security
    - firewall
    - ssh
    - fail2ban
    - hardening

dependencies:
  - role: common